# Generated by Django 5.1.4 on 2026-07-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademyArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=30, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("army", "Historia ya JWTZ"),
                            ("union", "Makumbusho ya Muungano"),
                            ("patriot", "Misingi ya Uzalendo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("body", models.TextField()),
                ("badge_label", models.CharField(blank=True, max_length=80)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
