# Generated by Django 5.1.4 on 2026-07-03 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_academyarticle"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=30, unique=True)),
                ("year", models.PositiveSmallIntegerField()),
                ("month_label", models.CharField(blank=True, max_length=40)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="MissionStepProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveSmallIntegerField()),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_steps",
                        to="api.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["step_number"],
                "unique_together": {("participant", "step_number")},
            },
        ),
    ]
