from django.urls import path

from api.views import (
    AcademyArticlesView,
    AdminDashboardView,
    AdminStoriesView,
    AdminStoryResolveView,
    CertificateGenerateView,
    CertificateVerifyView,
    ChemshaBongoView,
    ElderAudioView,
    LeaderboardView,
    LiveImpactView,
    MapStatsView,
    MatchView,
    MissionChatView,
    MissionProgressView,
    MissionStepCompleteView,
    OralStorySubmitView,
    QuizQuestionsView,
    QuizSubmitView,
    RegisterView,
    ReportCreateView,
    AdminReportsView,
    AdminReportResolveView,
    LoginView,
    TimelineEventsView,
    UserMeView,
    UssdBotView,
    WhatsAppBotView,
)

urlpatterns = [
    path("users/register", RegisterView.as_view(), name="register"),
    path("users/login", LoginView.as_view(), name="login"),
    path("users/me", UserMeView.as_view(), name="user-me"),
    path("users/me/progress", MissionProgressView.as_view(), name="mission-progress"),
    path("users/me/steps/<int:step_number>/complete", MissionStepCompleteView.as_view(), name="step-complete"),
    path("matching/match", MatchView.as_view(), name="match"),
    path("missions/<uuid:mission_id>/chat", MissionChatView.as_view(), name="mission-chat"),
    path("quiz/questions", QuizQuestionsView.as_view(), name="quiz-questions"),
    path("quiz/chemsha-bongo", ChemshaBongoView.as_view(), name="chemsha-bongo"),
    path("missions/<uuid:mission_id>/quiz/submit", QuizSubmitView.as_view(), name="quiz-submit"),
    path("certificates/generate", CertificateGenerateView.as_view(), name="certificate-generate"),
    path("certificates/verify/<str:cert_code>", CertificateVerifyView.as_view(), name="certificate-verify"),
    path("academy/articles", AcademyArticlesView.as_view(), name="academy-articles"),
    path("timeline/events", TimelineEventsView.as_view(), name="timeline-events"),
    path("leaderboard/youth", LeaderboardView.as_view(), name="leaderboard-youth"),
    path("reports", ReportCreateView.as_view(), name="report-create"),
    path("admin/reports", AdminReportsView.as_view(), name="admin-reports"),
    path("admin/reports/<uuid:report_id>/resolve", AdminReportResolveView.as_view(), name="admin-report-resolve"),
    path("admin/stories", AdminStoriesView.as_view(), name="admin-stories"),
    path("admin/stories/<uuid:story_id>/resolve", AdminStoryResolveView.as_view(), name="admin-story-resolve"),
    path("stories/submit", OralStorySubmitView.as_view(), name="story-submit"),
    path("impact/live", LiveImpactView.as_view(), name="impact-live"),
    path("admin/dashboard", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("map/stats", MapStatsView.as_view(), name="map-stats"),
    path("audio/archive", ElderAudioView.as_view(), name="audio-archive"),
    path("channels/whatsapp/chat", WhatsAppBotView.as_view(), name="whatsapp-bot"),
    path("channels/ussd/session", UssdBotView.as_view(), name="ussd-bot"),
]
