from django.urls import path

from api.views import (
    AcademyArticlesView,
    AdminDashboardView,
    AdminGalaToggleView,
    AdminStoriesView,
    AdminStoryResolveView,
    CertificateGenerateView,
    CertificateVerifyView,
    ChemshaBongoView,
    ElderAudioView,
    LeaderboardView,
    LiveImpactView,
    MapStatsView,
    MatchView,
    MissionChatView,
    MissionProgressView,
    MissionStepCompleteView,
    OralStorySubmitView,
    PlatformStatusView,
    QuizQuestionsView,
    QuizSubmitView,
    RegisterView,
    ReportCreateView,
    AdminReportsView,
    AdminReportResolveView,
    LoginView,
    TimelineEventsView,
    UserMeView,
    UssdBotView,
    WhatsAppBotView,
)
from api.extension_views import (
    AdminElderRadioToggleView,
    AdminElderStoriesView,
    AdminElderStoryResolveView,
    AdminRewardDisburseView,
    AdminRewardsView,
    CertificateListView,
    CertificatePdfView,
    ElderRadioTop10View,
    ElderStoriesPublicView,
    ElderStorySubmitView,
    GalaCeremonyView,
    InstitutionsListView,
    PartnerDashboardView,
    RadioPartnerView,
    UssdGatewayView,
    WhatsAppWebhookView,
)

urlpatterns = [
    path("users/register", RegisterView.as_view(), name="register"),
    path("users/login", LoginView.as_view(), name="login"),
    path("users/me", UserMeView.as_view(), name="user-me"),
    path("users/me/progress", MissionProgressView.as_view(), name="mission-progress"),
    path("users/me/steps/<int:step_number>/complete", MissionStepCompleteView.as_view(), name="step-complete"),
    path("matching/match", MatchView.as_view(), name="match"),
    path("missions/<uuid:mission_id>/chat", MissionChatView.as_view(), name="mission-chat"),
    path("quiz/questions", QuizQuestionsView.as_view(), name="quiz-questions"),
    path("quiz/chemsha-bongo", ChemshaBongoView.as_view(), name="chemsha-bongo"),
    path("missions/<uuid:mission_id>/quiz/submit", QuizSubmitView.as_view(), name="quiz-submit"),
    path("certificates/generate", CertificateGenerateView.as_view(), name="certificate-generate"),
    path("certificates/mine", CertificateListView.as_view(), name="certificate-list"),
    path("certificates/<str:cert_code>/pdf", CertificatePdfView.as_view(), name="certificate-pdf"),
    path("certificates/verify/<str:cert_code>", CertificateVerifyView.as_view(), name="certificate-verify"),
    path("academy/articles", AcademyArticlesView.as_view(), name="academy-articles"),
    path("timeline/events", TimelineEventsView.as_view(), name="timeline-events"),
    path("leaderboard/youth", LeaderboardView.as_view(), name="leaderboard-youth"),
    path("reports", ReportCreateView.as_view(), name="report-create"),
    path("admin/reports", AdminReportsView.as_view(), name="admin-reports"),
    path("admin/reports/<uuid:report_id>/resolve", AdminReportResolveView.as_view(), name="admin-report-resolve"),
    path("admin/stories", AdminStoriesView.as_view(), name="admin-stories"),
    path("admin/stories/<uuid:story_id>/resolve", AdminStoryResolveView.as_view(), name="admin-story-resolve"),
    path("admin/gala/<uuid:participant_id>", AdminGalaToggleView.as_view(), name="admin-gala-toggle"),
    path("stories/submit", OralStorySubmitView.as_view(), name="story-submit"),
    path("elders/submit", ElderStorySubmitView.as_view(), name="elder-submit"),
    path("elders/stories", ElderStoriesPublicView.as_view(), name="elder-stories"),
    path("elders/radio-top10", ElderRadioTop10View.as_view(), name="elder-radio-top10"),
    path("admin/elders", AdminElderStoriesView.as_view(), name="admin-elders"),
    path("admin/elders/<uuid:story_id>/resolve", AdminElderStoryResolveView.as_view(), name="admin-elder-resolve"),
    path("admin/elders/<uuid:story_id>/radio", AdminElderRadioToggleView.as_view(), name="admin-elder-radio"),
    path("admin/rewards", AdminRewardsView.as_view(), name="admin-rewards"),
    path("admin/rewards/<uuid:reward_id>/disburse", AdminRewardDisburseView.as_view(), name="admin-reward-disburse"),
    path("institutions", InstitutionsListView.as_view(), name="institutions"),
    path("partner/dashboard", PartnerDashboardView.as_view(), name="partner-dashboard"),
    path("partner/radio", RadioPartnerView.as_view(), name="radio-partner"),
    path("gala/ceremony", GalaCeremonyView.as_view(), name="gala-ceremony"),
    path("impact/live", LiveImpactView.as_view(), name="impact-live"),
    path("platform/status", PlatformStatusView.as_view(), name="platform-status"),
    path("admin/dashboard", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("map/stats", MapStatsView.as_view(), name="map-stats"),
    path("audio/archive", ElderAudioView.as_view(), name="audio-archive"),
    path("channels/whatsapp/chat", WhatsAppBotView.as_view(), name="whatsapp-bot"),
    path("channels/whatsapp/webhook", WhatsAppWebhookView.as_view(), name="whatsapp-webhook"),
    path("channels/ussd/session", UssdBotView.as_view(), name="ussd-bot"),
    path("channels/ussd/gateway", UssdGatewayView.as_view(), name="ussd-gateway"),
]
